version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5020:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=TodoListDb
      - MongoDbSettings__CollectionName=Todos
    depends_on:
      - mongodb
    networks:
      - app-network

  tests:
    build:
      context: ./backend
      dockerfile: ./Tests/Dockerfile.tests
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=TodoListTestDb
      - MongoDbSettings__CollectionName=TodosTest
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/todo-list
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5020
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
